import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useAccount, useDisconnect, useSignMessage } from "wagmi";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { isConnected } = useAccount();
  const { disconnect } = useDisconnect();
  const { signMessageAsync } = useSignMessage();
  console.log("is connected :: ", isConnected);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isConnected ? (
          <button onClick={() => disconnect()}>Disconnect</button>
        ) : (
          <ConnectButton />
        )}
        <button onClick={() => signMessageAsync({ message: "yo!" })}>
          Sign message
        </button>
      </main>
    </div>
  );
};

export default Home;
